#!/usr/bin/env python

Import("env")
Import("env_modules")

env_1d = env_modules.Clone()

env_1d.add_source_files(env.modules_sources, "*.cpp")
env_1d.add_source_files(env.modules_sources, "physics/*.cpp")
