#!/usr/bin/env python
import os
from glob import glob
from pathlib import Path

# TODO: Do not copy environment after godot-cpp/test is updated <https://github.com/godotengine/godot-cpp/blob/master/test/SConstruct>.
env = SConscript("godot-cpp/SConstruct")

# Add source files.
env.Append(CPPPATH=["./,nodes/,nodes/physics/"])
sources = Glob("*.cpp") + Glob("nodes/*.cpp") + Glob("nodes/physics/*.cpp")

# Find gdextension path even if the directory or extension is renamed.
# Example: project/addons/example/example.gdextension
#(extension_path,) = glob("project/addons/*/*.gdextension")

# Find the addon path (e.g. project/addons/example).
#addon_path = Path(extension_path).parent
#addon_path = "1d"

# Find the extension name from the gdextension file (e.g. example).
extension_name = "1d"
#extension_name = Path(extension_path).stem

# TODO: Cache is disabled currently.
# scons_cache_path = os.environ.get("SCONS_CACHE")
# if scons_cache_path != None:
#     CacheDir(scons_cache_path)
#     print("Scons cache enabled... (path: '" + scons_cache_path + "')")

# Create the library target (e.g. libexample.linux.debug.x86_64.so).
debug_or_release = "release" if env["target"] == "template_release" else "debug"
if env["platform"] == "macos":
    library = env.SharedLibrary(
        "../bin/lib{0}.{1}.{2}.framework/{0}.{1}.{2}".format(
            extension_name,
            env["platform"],
            debug_or_release,
        ),
        source=sources,
    )
else:
    library = env.SharedLibrary(
        "../bin/lib{}.{}.{}.{}{}".format(
            extension_name,
            env["platform"],
            debug_or_release,
            env["arch_suffix"],
            env["SHLIBSUFFIX"],
        ),
        source=sources,
    )

Default(library)
